'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {

    await queryInterface.bulkInsert('Plants', [{
      name: "Dumb Cane",
      botanicalName: "Dieffenbachia",
      location: "indoor",
      water: "moderate",
      sunlight: "medium to bright light",
      plantType: "",
      humidity: "",
      tempLow: 65,
      tempHigh: 70,
      hardiness: 60,
      pH: "n/a",
      cycle: "n/a",
      hardinessZone: "10-12",
      lastPotted: "2020-05-30",
      soilContent: "peat, perlite, potting mix",
      links: "https://plantcaretoday.com/dieffenbachia-plant-care.html",
      notes: "n/a",
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      name: "Rubber Plant",
      botanicalName: "",
      location: "indoor",
      water: "moderate",
      sunlight: "bright light",
      plantType: "",
      humidity: "",
      tempLow: 60,
      tempHigh: 80,
      hardiness: 50,
      pH: "n/a",
      soilContent: "",
      cycle: "n/a",
      hardinessZone: "10-11",
      lastPotted: null,
      links: "https://www.proflowers.com/blog/rubber-plant-care, https://www.today.com/home/easiest-indoor-house-plants-won-t-die-you-t73006",
      notes: "let it dry out",
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      name: "Coleus",
      botanicalName: "",
      location: "outdoor",
      water: "moist",
      sunlight: "part sun, full sun",
      plantType: "",
      humidity: "",
      tempLow: 60,
      tempHigh: 90,
      hardiness: 50,
      pH: 7,
      soilContent: "",
      cycle: "n/a",
      hardinessZone: "10-11",
      lastPotted: null,
      links: "https://www.doityourself.com/stry/mistakes-to-avoid-when-growing-a-coleus",
      notes: "below 40 and the plant will be damaged",
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      name: "Citronella",
      botanicalName: "",
      location: "outdoor",
      water: "moderate to dry",
      sunlight: "",
      plantType: "",
      humidity: "",
      tempLow: 60,
      tempHigh: 70,
      hardiness: 50,
      pH: "n/a",
      soilContent: "",
      cycle: "perennial",
      hardinessZone: "9-11",
      lastPotted: null,
      links: "https://www.gardenguides.com/90515-care-citronella-plants-fall.html, https://bonnieplants.com/how-to-grow/growing-mosquito-plants/", 
      notes: "drought tolerant",
      createdAt: new Date(),
      updatedAt: new Date()
    }, {
      name: "Rosemary",
      botanicalName: "",
      location: "outdoor",
      water: "dry",
      sunlight: "full sun",
      plantType: "herb",
      humidity: "",
      tempLow: 30,
      tempHigh: 90,
      hardiness: 20,
      pH: "n/a",
      soilContent: "sandy, loamy",
      cycle: "",
      hardinessZone: "7-10",
      lastPotted: null,
      links: "https://bonnieplants.com/how-to-grow/growing-rosemary/, https://www.almanac.com/plant/rosemary",
      notes: "can handle temp being 0, but not sustained",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Lavender",
      botanicalName: "",
      location: "indoor",
      water: "dry",
      sunlight: "full sun",
      plantType: "",
      humidity: "",
      tempLow: 10,
      tempHigh: 90,
      hardiness: 20,
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "5-8",
      lastPotted: null,
      links: "https://homeguides.sfgate.com/climate-grow-english-lavender-71815.html",
      notes: "check the variety of lavender, as some can't tolerate temps below 40, while others can handle 10 to -20",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Italian Oregano",
      botanicalName: "",
      location: "outdoor",
      water: "moist",
      sunlight: "full sun, part shade",
      plantType: "herb",
      humidity: "",
      tempLow: 30,
      tempHigh: "",
      hardiness: 20,
      pH: "",
      soilContent: "",
      cycle: "perennial",
      hardinessZone: "5-10",
      lastPotted: null,
      links: "https://bonnieplants.com/product/italian-oregano/, https://www.thespruce.com/growing-oregano-plants-1402818",
      notes: "allow soil to dry out between waterings",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Greek Oregano",
      botanicalName: "",
      location: "outdoor",
      water: "moist",
      sunlight: "full sun, part shade",
      plantType: "herb",
      humidity: "",
      tempLow: 20,
      tempHigh: "",
      hardiness: -30,
      pH: "",
      soilContent: "",
      cycle: "perennial",
      hardinessZone: "4-8",
      lastPotted: null,
      links: "https://bonnieplants.com/product/greek-oregano/, https://www.thespruce.com/growing-oregano-plants-1402818",
      notes: "allow soil to dry out between waterings",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Lemon Thyme",
      botanicalName: "",
      location: "outdoor",
      water: "",
      sunlight: "full sun to part shade",
      plantType: "",
      humidity: "",
      tempLow: 20,
      tempHigh: "",
      hardiness: 10,
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "7 - 9",
      lastPotted: null,
      links: "https://bonnieplants.com/product/lemon-thyme/",
      notes: "Perennial in zones 7 to 9, plant spacing 18 to 24 inches apart",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Romaine Lettuce",
      botanicalName: "",
      location: "outdoor",
      water: "moist",
      sunlight: "full sun to part shade",
      plantType: "",
      humidity: "",
      tempLow: 25,
      tempHigh: 90,
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "cold weather plant",
      createdAt: new Date(),
      updatedAt: new Date()
  },
    {
      name: "Boxwood",
      botanicalName: "",
      location: "outdoor",
      water: "when dry",
      sunlight: "full sun",
      plantType: "",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: -30,
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "Also named Buxus, Green Velvet, height 24-36', space 36'",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Lilac",
      botanicalName: "",
      location: "outdoor",
      water: "when dry",
      sunlight: "full sun",
      plantType: "",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: -40,
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "Also named 'syringa patula', 'Miss Kim', height 3-5', space 5', blooms early spring to summer",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Spinach",
      botanicalName: "",
      location: "outdoor",
      water: "moist",
      sunlight: "full sun, part shade",
      plantType: "herb",
      humidity: "",
      tempLow: 20,
      tempHigh: "",
      hardiness: 20,
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "https://bonnieplants.com/product/bonnie-spinach/?gclid=EAIaIQobChMIzYXQsZ_L6QIVkIbACh06_AC5EAAYASAAEgLtOPD_BwE&cmp=kid/BonniePlants/Google_SEM/Brand/G|BonniePlants|Search|Generic|Vegetables/G|BonniePlants|Search|Generic|Vegetables|Spinach&s_kwcid=AL!4676!3!426170300098!p!!g!!grow%20spinach&ef_id=EAIaIQobChMIzYXQsZ_L6QIVkIbACh06_AC5EAAYASAAEgLtOPD_BwE:G:s&s_kwcid=AL!4676!3!426170300098!p!!g!!grow%20spinach",
      notes: "",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Flat Leaf Parsley",
      botanicalName: "",
      location: "",
      water: "moist",
      sunlight: "sun to part shade",
      plantType: "",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: 25,
      pH: "",
      soilContent: "",
      cycle: "biennial",
      hardinessZone: "",
      lastPotted: null,
      links: "https://bonnieplants.com/product/flat-italian-parsley/",
      notes: "Space 12 to 20 inches apart, depending on type, plant size 1 foot tall",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Arugula",
      botanicalName: "",
      location: "",
      water: "moist",
      sunlight: "",
      plantType: "vegetable",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: 30,
      pH: "",
      soilContent: "",
      cycle: "annual",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "Cool season plant. Leafy plants grow 6 to 12 inches tall while in the harvest stage. Once they bolt in late spring or early summer, the bloom stalks may grow 24 to 36 inches with (edible!) tan-white flowers on top, which signals that it is time to make room for warm-weather crops. However, some gardeners continue to harvest the leaves even from the tall plants, liking the stronger taste. You can even cut them back and pick some more until you finally tire of that and then pull them up and wait until fall to plant again.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Basil",
      botanicalName: "",
      location: "outdoor",
      water: "moist",
      sunlight: "full sun to part sun",
      plantType: "herb",
      humidity: "",
      tempLow: 50,
      tempHigh: "",
      hardiness: 40,
      pH: "",
      soilContent: "",
      cycle: "annual",
      hardinessZone: "10 - 11",
      lastPotted: null,
      links: "",
      notes: "",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Sweet Potato Vine",
      botanicalName: "",
      location: "",
      water: "moist",
      sunlight: "sun, part sun, shade",
      plantType: "",
      humidity: "",
      tempLow: 50,
      tempHigh: 50,
      hardiness: 40,
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "http://www.costafarms.com/plants/sweet-potato-vine, https://www.gardendesign.com/vines/sweet-potato-vine.html",
      notes: "For containers, plant in a high quality all-purpose potting soil.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Artillery plant",
      botanicalName: "",
      location: "indoor, outdoor",
      water: "",
      sunlight: "",
      plantType: "",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "11 - 12",
      lastPotted: null,
      links: "https://www.gardeningknowhow.com/houseplants/pilea-plants/growing-artillery-plants.htm",
      notes: "pilea microphylla",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Chinese Money plant",
      botanicalName: "",
      location: "indoor",
      water: "moderate to dry",
      sunlight: "bright light, indirect light",
      plantType: "",
      humidity: "",
      tempLow: "65",
      tempHigh: "",
      hardiness: "none",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: "2020-07-18",
      links: "https://greeneryunlimited.co/blogs/plant-care/pilea-peperomioides-care, https://bloomscape.com/plant-care-guide/pilea/#g1, https://savvygardening.com/pilea-peperomioides-care/",
      notes: "Pilea peperomioides",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Spider plant",
      botanicalName: "",
      location: "indoor",
      water: "moderate",
      sunlight: "bright light, medium light",
      plantType: "",
      humidity: "",
      tempLow: "60",
      tempHigh: "75",
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Haworthias",
      botanicalName: "",
      location: "indoor",
      water: "",
      sunlight: "",
      plantType: "succulent",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Pothos",
      botanicalName: "",
      location: "indoor",
      water: "",
      sunlight: "",
      plantType: "",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Fiddleleaf fig plant",
      botanicalName: "ficus lyrata",
      location: "indoor",
      water: "moderate to moist",
      sunlight: "bright, filtered light",
      plantType: "",
      humidity: "",
      tempLow: 60,
      tempHigh: 80,
      hardiness: "",
      pH: "",
      soilContent: "Any good, fast-draining potting soil will likely do",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "https://www.thespruce.com/grow-fiddle-leaf-fig-indoors-1902756, https://www.gardenista.com/posts/10-things-nobody-tells-fiddle-leaf-fig-trees-houseplant-growing-care-guide/",
      notes: "in the wild thrive in warm and wet conditions",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Bird of paradise",
      botanicalName: "",
      location: "outdoor",
      water: "moderate",
      sunlight: "very bright light, part sun",
      plantType: "",
      humidity: "",
      tempLow: 50,
      tempHigh: 80,
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "",
      lastPotted: null,
      links: "",
      notes: "https://www.fieldnotesbystudioplants.com/houseplants/bird-of-paradise-plant-care-strelitzia",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Red Aglaonema",
      botanicalName: "Aglaonema",
      location: "indoor",
      water: "moderate to dry",
      sunlight: "low to bright light",
      plantType: "",
      humidity: "",
      tempLow: 65,
      tempHigh: "",
      hardiness: 65,
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "10 - 11",
      lastPotted: null,
      links: "https://www.thespruce.com/grow-aglaonema-houseplants-1902734",
      notes: "mist",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Pincushion peperomia",
      botanicalName: "Peperomia ferreyrae",
      location: "indoor",
      water: "",
      humidity: "yes",
      sunlight: "bright light",
      plantType: "",
      humidity: "",
      tempLow: 65,
      tempHigh: 75,
      hardiness: 50,
      pH: "",
      soilContent: "",
      cycle: "perennial",
      hardinessZone: "9 - 11",
      lastPotted: null,
      links: "https://plantcaretoday.com/peperomia-ferreyrae.html, https://www.houseplantsexpert.com/peperomia-ferreyrae.html",
      notes: "Use a potting mix prepared with two parts peat and one part perlite or sand for best results.",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Umbrella plant",
      botanicalName: "Schefflera arboricola",
      location: "indoor",
      water: "moist",
      humidity: "yes",
      sunlight: "bright, indirect light",
      plantType: "",
      humidity: "",
      tempLow: "",
      tempHigh: "",
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "10 - 11",
      lastPotted: null,
      links: "https://www.thespruce.com/grow-schefflera-plants-inside-1902771",
      notes: ""
    },
    {
      name: "Bamboo plant",
      botanicalName: "Dracaena sanderiana",
      location: "indoor",
      water: "moderate",
      sunlight: "indirect light",
      plantType: "",
      humidity: "",
      tempLow: 65,
      tempHigh: 95,
      hardiness: "",
      pH: "",
      soilContent: "",
      cycle: "",
      hardinessZone: "10-11",
      lastPotted: null,
      links: "https://www.proflowers.com/blog/lucky-bamboo-care, https://bambooplantshq.com/lucky-bamboo-turning-white-or-pale/",
      notes: "",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Sensitive plant",
      botanicalName: "Mimosa pudica",
      location: "indoor",
      water: "moderate",
      sunlight: "bright",
      plantType: "houseplant",
      humidity: "moderate",
      tempLow: "65",
      tempHigh: "85",
      hardiness: "60",
      pH: null,
      soilContent: "loamy, peat moss",
      cycle: null,
      hardinessZone: "60",
      lastPotted: null,
      links: "https://www.youtube.com/watch?v=Fl-3lpYXnYg, https://homeguides.sfgate.com/care-sensitive-plant-mimosa-pudica-67276.html",
      notes: "allow to dry and wilt a little but watch closely. do not overwater. yellow leaves appear when overwatered",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Stapelia",
      botanicalName: "Stapelia",
      location: null,
      water: "dry",
      sunlight: "medium",
      plantType: "succulent",
      humidity: null,
      tempLow: "95",
      tempHigh: "50",
      hardiness: "50",
      tolerance: null,
      pH: null,
      soilContent: "airy, well-drained soil",
      cycle: null,
      hardinessZone: "50",
      lastPotted: "2019-01-01",
      links: "http://pza.sanbi.org/stapelia, https://plantcaretoday.com/carrion-flower-stapelia.html",
      notes: "water once every 3-4 weeks in the winter, once every other week in the growing season. watch for mealy bugs, though they tend to appear from overwatering",
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      name: "Janet Craig Compacta",
      botanicalName: "Dracaena deremensis",
      location: "indoor",
      water: "moderate",
      sunlight: "low",
      plantType: "houseplant",
      humidity: "moderate",
      tempLow: "80",
      tempHigh: "65",
      hardiness: "40",
      pH: null,
      soilContent: null,
      cycle: null,
      hardinessZone: "40",
      lastPotted: null,
      links: "https://plantcaretoday.com/dracaena-compacta.html",
      notes: "slow growing",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Sansevieria",
      botanicalName: "Sansevieria trifasciata",
      location: "indoor",
      water: "moderate",
      sunlight: "low",
      plantType: "houseplant",
      humidity: "moderate",
      tempLow: "80",
      tempHigh: "65",
      hardiness: "45",
      pH: null,
      soilContent: null,
      cycle: null,
      hardinessZone: "45",
      lastPotted: null,
      links: "https://www.joyusgarden.com/sansevierias-snake-plant-care/",
      notes: "slow growing. make sure soil is completely dry before watering again. water every 2-8 weeks, less often in winter.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Rabbit's Foot Fern",
      botanicalName: "Davallia Fejeensis",
      location: "indoor",
      water: "moderate",
      sunlight: "medium",
      plantType: "houseplant",
      humidity: "moderate",
      tempLow: "80",
      tempHigh: "65",
      hardiness: "55",
      pH: null,
      soilContent: "50% peat and chopped bark",
      cycle: null,
      hardinessZone: "55",
      lastPotted: null,
      links: "https://www.epicgardening.com/rabbits-foot-fern/",
      notes: "Water when top inch of soil is dry. Shallow pots work well for growing this houseplant. Make sure to change the pot every few years.",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: "Purple Waffle Plant",
      botanicalName: "hemigraphis alternata",
      location: "indoor",
      water: "moist",
      sunlight: "bright",
      plantType: "houseplant",
      humidity: "high",
      tempLow: "80",
      tempHigh: "55",
      hardiness: "55",
      pH: null,
      soilContent: null,
      cycle: null,
      hardinessZone: "55",
      lastPotted: null,
      links: "https://lunarly.com/blogs/plant-care/grow-a-vibrant-purple-waffle-plant",
      notes: "low growing",
      createdAt: new Date(),
      updatedAt: new Date(),
    }
  ]);
  
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
